In [4]:
import numpy as np

In [5]:
arr = np.random.randint(1,10, size=(2,5))
arr

array([[1, 2, 5, 5, 8],
       [9, 8, 8, 1, 5]])

In [6]:
print(arr.mean())
print(np.mean(arr))

5.2
5.2


In [7]:
#axis=1 매개변수를 추가하면 행의 데이터들만 연산한다.
print(np.mean(arr,axis=1))

[4.2 6.2]


In [8]:
#mean함수에 arr자체를 집어 넣으면 세로 값인 열 데이터들만 연산한다
#안되는거같음

In [9]:
arr

array([[1, 2, 5, 5, 8],
       [9, 8, 8, 1, 5]])

In [10]:
#sqrt함수 제곱근으 구한다
print(np.sqrt(arr))

[[1.         1.41421356 2.23606798 2.23606798 2.82842712]
 [3.         2.82842712 2.82842712 1.         2.23606798]]


In [11]:
arr= np.array([-1,2,-3,4,-5])
arr

array([-1,  2, -3,  4, -5])

In [12]:
np.abs(arr)

array([1, 2, 3, 4, 5])

In [13]:
data = np.loadtxt('ratings.txt', delimiter="::", dtype="int")
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [14]:
print("배열의 크기 : ",data.shape)
print("배열의 차원 : ",data.ndim)
print("배열의 개수 : ",data.size)

배열의 크기 :  (1000209, 4)
배열의 차원 :  2
배열의 개수 :  4000836


In [15]:
print(data[:,2].mean())
print(np.mean(data[:,2]))

3.581564453029317
3.581564453029317


In [16]:
user_id=np.unique(data[:,0])
user_id

array([   1,    2,    3, ..., 6038, 6039, 6040])

In [17]:
for i in user_id:
    for j in range(1,6041):
        if i==j :
            a=data[j,2]
            print(a.mean())

3.0
3.0
4.0
5.0
3.0
5.0
5.0
4.0
4.0
5.0
4.0
4.0
4.0
5.0
4.0
3.0
4.0
5.0
4.0
3.0
3.0
5.0
5.0
3.0
5.0
4.0
4.0
4.0
3.0
4.0
4.0
4.0
4.0
4.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
4.0
4.0
5.0
5.0
4.0
5.0
4.0
4.0
4.0
4.0
5.0
4.0
4.0
3.0
4.0
4.0
5.0
3.0
3.0
3.0
5.0
4.0
3.0
3.0
2.0
5.0
3.0
4.0
3.0
4.0
2.0
3.0
2.0
3.0
4.0
3.0
5.0
3.0
5.0
4.0
2.0
4.0
5.0
5.0
4.0
5.0
4.0
4.0
2.0
3.0
5.0
3.0
3.0
4.0
5.0
4.0
3.0
3.0
3.0
5.0
4.0
4.0
4.0
5.0
4.0
5.0
3.0
3.0
4.0
3.0
3.0
2.0
5.0
4.0
5.0
3.0
5.0
5.0
3.0
3.0
4.0
4.0
2.0
5.0
5.0
3.0
4.0
4.0
5.0
3.0
2.0
3.0
4.0
3.0
4.0
3.0
4.0
3.0
3.0
5.0
4.0
3.0
5.0
5.0
4.0
1.0
3.0
3.0
2.0
5.0
5.0
4.0
4.0
4.0
5.0
3.0
4.0
4.0
3.0
4.0
4.0
3.0
3.0
3.0
5.0
5.0
5.0
4.0
3.0
5.0
4.0
2.0
3.0
3.0
5.0
2.0
5.0
1.0
5.0
4.0
2.0
3.0
4.0
3.0
4.0
4.0
4.0
3.0
3.0
5.0
3.0
5.0
4.0
5.0
4.0
5.0
3.0
2.0
5.0
4.0
3.0
4.0
1.0
4.0
4.0
2.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
3.0
4.0
5.0
5.0
3.0
4.0
4.0
2.0
4.0
5.0
4.0
4.0
4.0
4.0
5.0
4.0
5.0
3.0
4.0
4.0
4.0
5.0
5.0
4.0
2.0
5.0
5.0
4.0
4.0
4.0
4.0
5.0
1.0
5.0


5.0
3.0
4.0
4.0
4.0
5.0
3.0
3.0
5.0
5.0
5.0
4.0
4.0
2.0
3.0
5.0
4.0
4.0
5.0
4.0
3.0
5.0
4.0
4.0
4.0
1.0
4.0
4.0
3.0
3.0
2.0
3.0
2.0
3.0
5.0
4.0
3.0
4.0
5.0
3.0
3.0
3.0
2.0
3.0
2.0
4.0
4.0
1.0
2.0
5.0
5.0
3.0
5.0
4.0
4.0
5.0
3.0
3.0
1.0
5.0
5.0
3.0
3.0
5.0
5.0
4.0
5.0
3.0
4.0
3.0
4.0
2.0
3.0
4.0
5.0
5.0
3.0
2.0
4.0
4.0
4.0
5.0
4.0
4.0
1.0
3.0
2.0
3.0
2.0
4.0
4.0
4.0
4.0
4.0
2.0
5.0
5.0
5.0
5.0
4.0
2.0
2.0
4.0
1.0
3.0
4.0
3.0
5.0
4.0
3.0
4.0
1.0
3.0
3.0
5.0
4.0
3.0
1.0
4.0
2.0
4.0
3.0
5.0
3.0
2.0
3.0
4.0
5.0
3.0
5.0
3.0
3.0
3.0
3.0
2.0
4.0
3.0
4.0
3.0
4.0
5.0
5.0
4.0
4.0
4.0
3.0
5.0
3.0
2.0
5.0
5.0
5.0
4.0
4.0
4.0
5.0
5.0
4.0
4.0
3.0
5.0
3.0
3.0
3.0
5.0
3.0
1.0
3.0
4.0
1.0
4.0
3.0
3.0
3.0
5.0
1.0
5.0
1.0
3.0
1.0
1.0
4.0
2.0
1.0
2.0
3.0
3.0
2.0
3.0
2.0
3.0
3.0
3.0
2.0
4.0
5.0
4.0
4.0
4.0
4.0
3.0
2.0
2.0
3.0
4.0
1.0
4.0
3.0
2.0
3.0
4.0
4.0
3.0
4.0
4.0
4.0
4.0
4.0
3.0
3.0
2.0
4.0
2.0
4.0
3.0
3.0
2.0
1.0
2.0
3.0
3.0
3.0
3.0
3.0
4.0
3.0
4.0
4.0
2.0
5.0
2.0
4.0
3.0
4.0
4.0
4.0
3.0
4.0
2.0
2.0


2.0
4.0
3.0
3.0
4.0
5.0
3.0
4.0
3.0
5.0
5.0
4.0
2.0
3.0
5.0
3.0
5.0
3.0
5.0
5.0
3.0
5.0
4.0
2.0
2.0
5.0
5.0
3.0
1.0
5.0
3.0
4.0
3.0
5.0
4.0
4.0
1.0
5.0
3.0
3.0
3.0
4.0
2.0
3.0
4.0
5.0
2.0
4.0
5.0
3.0
4.0
2.0
4.0
2.0
2.0
3.0
5.0
4.0
2.0
5.0
3.0
3.0
3.0
4.0
5.0
3.0
3.0
4.0
4.0
1.0
4.0
4.0
4.0
4.0
3.0
4.0
4.0
2.0
5.0
2.0
4.0
4.0
3.0
4.0
4.0
2.0
5.0
3.0
4.0
5.0
3.0
3.0
5.0
3.0
4.0
5.0
4.0
5.0
1.0
5.0
4.0
4.0
4.0
5.0
3.0
5.0
3.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
1.0
3.0
5.0
5.0
2.0
5.0
4.0
4.0
4.0
4.0
3.0
4.0
4.0
2.0
2.0
5.0
5.0
2.0
4.0
5.0
5.0
3.0
4.0
3.0
4.0
5.0
4.0
5.0
2.0
4.0
3.0
4.0
5.0
3.0
4.0
4.0
5.0
4.0
4.0
5.0
3.0
5.0
3.0
3.0
5.0
5.0
1.0
4.0
5.0
4.0
5.0
3.0
4.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
3.0
4.0
4.0
5.0
4.0
4.0
3.0
3.0
4.0
5.0
5.0
3.0
5.0
4.0
5.0
4.0
5.0
4.0
4.0
5.0
2.0
5.0
4.0
4.0
3.0
5.0
2.0
3.0
4.0
4.0
4.0
2.0
5.0
3.0
5.0
4.0
4.0
4.0
4.0
4.0
3.0
3.0
5.0
3.0
3.0
3.0
4.0
5.0
5.0
4.0
4.0
4.0
3.0
4.0
3.0
4.0
1.0
1.0
3.0
4.0
4.0
2.0
4.0
3.0
2.0
5.0
3.0
3.0
1.0
4.0
5.0
4.0
4.0
5.0
2.0
5.0


In [18]:
num=0
for i in user_id:
    num+=1
    if i==num :
        a=data[num,2]
        print(a.mean())

3.0
3.0
4.0
5.0
3.0
5.0
5.0
4.0
4.0
5.0
4.0
4.0
4.0
5.0
4.0
3.0
4.0
5.0
4.0
3.0
3.0
5.0
5.0
3.0
5.0
4.0
4.0
4.0
3.0
4.0
4.0
4.0
4.0
4.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
4.0
4.0
5.0
5.0
4.0
5.0
4.0
4.0
4.0
4.0
5.0
4.0
4.0
3.0
4.0
4.0
5.0
3.0
3.0
3.0
5.0
4.0
3.0
3.0
2.0
5.0
3.0
4.0
3.0
4.0
2.0
3.0
2.0
3.0
4.0
3.0
5.0
3.0
5.0
4.0
2.0
4.0
5.0
5.0
4.0
5.0
4.0
4.0
2.0
3.0
5.0
3.0
3.0
4.0
5.0
4.0
3.0
3.0
3.0
5.0
4.0
4.0
4.0
5.0
4.0
5.0
3.0
3.0
4.0
3.0
3.0
2.0
5.0
4.0
5.0
3.0
5.0
5.0
3.0
3.0
4.0
4.0
2.0
5.0
5.0
3.0
4.0
4.0
5.0
3.0
2.0
3.0
4.0
3.0
4.0
3.0
4.0
3.0
3.0
5.0
4.0
3.0
5.0
5.0
4.0
1.0
3.0
3.0
2.0
5.0
5.0
4.0
4.0
4.0
5.0
3.0
4.0
4.0
3.0
4.0
4.0
3.0
3.0
3.0
5.0
5.0
5.0
4.0
3.0
5.0
4.0
2.0
3.0
3.0
5.0
2.0
5.0
1.0
5.0
4.0
2.0
3.0
4.0
3.0
4.0
4.0
4.0
3.0
3.0
5.0
3.0
5.0
4.0
5.0
4.0
5.0
3.0
2.0
5.0
4.0
3.0
4.0
1.0
4.0
4.0
2.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
3.0
4.0
5.0
5.0
3.0
4.0
4.0
2.0
4.0
5.0
4.0
4.0
4.0
4.0
5.0
4.0
5.0
3.0
4.0
4.0
4.0
5.0
5.0
4.0
2.0
5.0
5.0
4.0
4.0
4.0
4.0
5.0
1.0
5.0


4.0
2.0
3.0
4.0
4.0
4.0
4.0
1.0
5.0
3.0
2.0
3.0
3.0
3.0
2.0
1.0
2.0
4.0
3.0
2.0
3.0
3.0
4.0
5.0
2.0
2.0
3.0
4.0
2.0
4.0
4.0
1.0
4.0
2.0
4.0
1.0
1.0
4.0
4.0
3.0
3.0
3.0
2.0
3.0
2.0
1.0
1.0
4.0
4.0
4.0
4.0
5.0
4.0
4.0
3.0
4.0
1.0
2.0
4.0
5.0
3.0
1.0
3.0
3.0
3.0
3.0
3.0
4.0
4.0
3.0
1.0
1.0
4.0
3.0
2.0
5.0
4.0
2.0
3.0
3.0
1.0
3.0
2.0
2.0
1.0
4.0
4.0
4.0
4.0
3.0
2.0
4.0
3.0
4.0
1.0
4.0
3.0
4.0
2.0
3.0
4.0
3.0
3.0
4.0
2.0
4.0
3.0
3.0
4.0
4.0
4.0
4.0
5.0
4.0
3.0
3.0
3.0
2.0
4.0
2.0
3.0
4.0
3.0
3.0
4.0
3.0
3.0
1.0
3.0
4.0
4.0
4.0
3.0
3.0
4.0
2.0
2.0
3.0
3.0
4.0
4.0
3.0
2.0
1.0
3.0
2.0
4.0
3.0
4.0
2.0
4.0
2.0
4.0
5.0
4.0
4.0
2.0
4.0
4.0
4.0
4.0
4.0
4.0
3.0
1.0
4.0
2.0
2.0
3.0
4.0
3.0
2.0
3.0
3.0
4.0
1.0
2.0
3.0
4.0
4.0
4.0
3.0
4.0
2.0
4.0
4.0
2.0
3.0
4.0
2.0
5.0
2.0
3.0
4.0
3.0
3.0
4.0
3.0
2.0
4.0
4.0
3.0
4.0
5.0
4.0
3.0
3.0
4.0
3.0
3.0
4.0
2.0
4.0
3.0
5.0
4.0
4.0
2.0
3.0
3.0
2.0
4.0
1.0
5.0
4.0
4.0
2.0
2.0
5.0
5.0
5.0
3.0
3.0
3.0
4.0
4.0
1.0
1.0
3.0
3.0
3.0
2.0
3.0
2.0
4.0
2.0
2.0
4.0
3.0
3.0


4.0
4.0
4.0
3.0
3.0
3.0
5.0
4.0
4.0
4.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
3.0
4.0
3.0
4.0
5.0
4.0
5.0
4.0
4.0
4.0
4.0
4.0
5.0
3.0
4.0
3.0
4.0
4.0
5.0
4.0
4.0
5.0
4.0
4.0
5.0
4.0
4.0
1.0
1.0
5.0
3.0
5.0
5.0
4.0
4.0
4.0
4.0
5.0
5.0
5.0
3.0
4.0
4.0
5.0
5.0
4.0
4.0
1.0
4.0
5.0
2.0
5.0
1.0
1.0
4.0
1.0
1.0
4.0
5.0
5.0
1.0
5.0
4.0
5.0
5.0
1.0
3.0
3.0
4.0
3.0
5.0
4.0
3.0
5.0
5.0
2.0
5.0
5.0
5.0
3.0
3.0
3.0
3.0
3.0
5.0
4.0
4.0
4.0
4.0
3.0
4.0
5.0
4.0
4.0
3.0
4.0
4.0
4.0
4.0
3.0
4.0
5.0
4.0
3.0
3.0
4.0
5.0
2.0
4.0
4.0
4.0
3.0
3.0
2.0
4.0
4.0
3.0
4.0
3.0
2.0
3.0
3.0
5.0
4.0
3.0
3.0
4.0
3.0
5.0
4.0
4.0
3.0
5.0
4.0
3.0
4.0
3.0
3.0
4.0
4.0
3.0
3.0
3.0
3.0
4.0
4.0
4.0
3.0
4.0
3.0
4.0
3.0
4.0
5.0
2.0
2.0
4.0
3.0
3.0
4.0
5.0
3.0
4.0
3.0
4.0
3.0
4.0
4.0
4.0
1.0
3.0
2.0
5.0
5.0
4.0
2.0
4.0
4.0
4.0
2.0
4.0
5.0
4.0
2.0
3.0
5.0
3.0
5.0
3.0
3.0
5.0
4.0
4.0
5.0
5.0
2.0
5.0
3.0
2.0
5.0
4.0
2.0
3.0
3.0
4.0
2.0
2.0
3.0
3.0
4.0
5.0
4.0
4.0
5.0
5.0
5.0
2.0
2.0
4.0
4.0
2.0
5.0
4.0
2.0
3.0


In [19]:
list1=[]
for i in user_id:
    a= np.mean(data[data[:,0]==i,2])
    list1.append(a)


print(list1)

data

[4.188679245283019, 3.7131782945736433, 3.9019607843137254, 4.190476190476191, 3.1464646464646466, 3.9014084507042255, 4.32258064516129, 3.884892086330935, 3.7358490566037736, 4.114713216957606, 3.2773722627737225, 3.8260869565217392, 3.388888888888889, 3.32, 3.3233830845771144, 3.0285714285714285, 4.075829383886256, 3.6491803278688524, 3.5725490196078433, 4.083333333333333, 2.909090909090909, 3.0673400673400675, 3.3157894736842106, 3.948529411764706, 3.7411764705882353, 2.96, 4.171428571428572, 3.7570093457943927, 3.5833333333333335, 3.488372093023256, 3.73109243697479, 3.625, 3.498721227621483, 3.8658536585365852, 3.54040404040404, 4.199430199430199, 3.69811320754717, 3.58, 3.564516129032258, 3.4479166666666665, 3.48, 3.74025974025974, 4.125, 3.6321243523316062, 2.946127946127946, 4.219512195121951, 3.909090909090909, 3.068561872909699, 3.712962962962963, 3.0697674418604652, 3.825, 3.5569620253164556, 4.2368421052631575, 4.025, 4.12, 3.970149253731343, 2.90625, 3.9725400457665905, 3.

In [27]:
list2 = []
for i in user_id:
    a= np.mean(data[data[:,0]==i,2])
    list1 = [i,a]
    print(list1,end="\n")
    list2.append(list1)    


[1, 4.188679245283019]
[2, 3.7131782945736433]
[3, 3.9019607843137254]
[4, 4.190476190476191]
[5, 3.1464646464646466]
[6, 3.9014084507042255]
[7, 4.32258064516129]
[8, 3.884892086330935]
[9, 3.7358490566037736]
[10, 4.114713216957606]
[11, 3.2773722627737225]
[12, 3.8260869565217392]
[13, 3.388888888888889]
[14, 3.32]
[15, 3.3233830845771144]
[16, 3.0285714285714285]
[17, 4.075829383886256]
[18, 3.6491803278688524]
[19, 3.5725490196078433]
[20, 4.083333333333333]
[21, 2.909090909090909]
[22, 3.0673400673400675]
[23, 3.3157894736842106]
[24, 3.948529411764706]
[25, 3.7411764705882353]
[26, 2.96]
[27, 4.171428571428572]
[28, 3.7570093457943927]
[29, 3.5833333333333335]
[30, 3.488372093023256]
[31, 3.73109243697479]
[32, 3.625]
[33, 3.498721227621483]
[34, 3.8658536585365852]
[35, 3.54040404040404]
[36, 4.199430199430199]
[37, 3.69811320754717]
[38, 3.58]
[39, 3.564516129032258]
[40, 3.4479166666666665]
[41, 3.48]
[42, 3.74025974025974]
[43, 4.125]
[44, 3.6321243523316062]
[45, 2.94612794

[427, 4.111111111111111]
[428, 3.9]
[429, 3.346820809248555]
[430, 3.9682539682539684]
[431, 3.630952380952381]
[432, 2.9863013698630136]
[433, 3.391304347826087]
[434, 4.023255813953488]
[435, 3.8333333333333335]
[436, 3.8345864661654137]
[437, 4.3076923076923075]
[438, 3.528239202657807]
[439, 3.902173913043478]
[440, 3.586206896551724]
[441, 3.9574468085106385]
[442, 3.8486997635933804]
[443, 3.823529411764706]
[444, 4.0]
[445, 3.3181818181818183]
[446, 4.8431372549019605]
[447, 4.837837837837838]
[448, 3.4347826086956523]
[449, 3.7222222222222223]
[450, 4.196078431372549]
[451, 4.511961722488039]
[452, 4.431818181818182]
[453, 3.66497461928934]
[454, 3.218045112781955]
[455, 4.2]
[456, 3.394904458598726]
[457, 3.7130801687763713]
[458, 3.5348837209302326]
[459, 3.6875]
[460, 3.3617021276595747]
[461, 3.224609375]
[462, 3.536723163841808]
[463, 3.0]
[464, 3.6097560975609757]
[465, 3.5405405405405403]
[466, 4.14070351758794]
[467, 3.2028985507246377]
[468, 3.730769230769231]
[469, 4.

[851, 3.5921052631578947]
[852, 4.117647058823529]
[853, 3.890909090909091]
[854, 3.027667984189723]
[855, 3.4126984126984126]
[856, 3.490566037735849]
[857, 4.171428571428572]
[858, 4.189473684210526]
[859, 3.450980392156863]
[860, 3.1666666666666665]
[861, 3.9375]
[862, 3.6724137931034484]
[863, 4.225806451612903]
[864, 4.050724637681159]
[865, 3.8095238095238093]
[866, 3.3333333333333335]
[867, 3.659090909090909]
[868, 3.6]
[869, 3.5154394299287413]
[870, 3.611111111111111]
[871, 3.9069767441860463]
[872, 3.635514018691589]
[873, 3.8430232558139537]
[874, 3.7857142857142856]
[875, 4.083333333333333]
[876, 3.828828828828829]
[877, 3.308056872037915]
[878, 4.142857142857143]
[879, 4.025]
[880, 3.4956521739130433]
[881, 2.9354485776805253]
[882, 4.0886075949367084]
[883, 3.4166666666666665]
[884, 4.01010101010101]
[885, 4.140625]
[886, 3.6285714285714286]
[887, 3.5104166666666665]
[888, 3.7777777777777777]
[889, 2.8405797101449277]
[890, 3.969298245614035]
[891, 3.7443946188340806]
[89

[1183, 3.682795698924731]
[1184, 3.338129496402878]
[1185, 3.6444444444444444]
[1186, 4.296116504854369]
[1187, 3.3870967741935485]
[1188, 4.161290322580645]
[1189, 3.76]
[1190, 4.037037037037037]
[1191, 4.295238095238095]
[1192, 4.379310344827586]
[1193, 2.782608695652174]
[1194, 3.325115562403698]
[1195, 3.71875]
[1196, 3.8839285714285716]
[1197, 4.166666666666667]
[1198, 3.656862745098039]
[1199, 3.631284916201117]
[1200, 3.5641025641025643]
[1201, 3.5757575757575757]
[1202, 3.5365384615384614]
[1203, 3.707152496626181]
[1204, 3.485294117647059]
[1205, 3.9411764705882355]
[1206, 3.5602836879432624]
[1207, 2.394822006472492]
[1208, 4.020833333333333]
[1209, 3.411764705882353]
[1210, 3.8974358974358974]
[1211, 3.863979848866499]
[1212, 3.8550724637681157]
[1213, 4.041666666666667]
[1214, 3.0217391304347827]
[1215, 4.034782608695652]
[1216, 3.6948356807511735]
[1217, 4.235294117647059]
[1218, 3.4553191489361703]
[1219, 3.6205357142857144]
[1220, 3.353846153846154]
[1221, 3.963800904977

[1519, 3.528735632183908]
[1520, 4.0]
[1521, 3.263888888888889]
[1522, 3.641025641025641]
[1523, 3.717391304347826]
[1524, 3.7351778656126484]
[1525, 3.6633663366336635]
[1526, 4.15625]
[1527, 3.1538461538461537]
[1528, 4.086956521739131]
[1529, 3.7666666666666666]
[1530, 3.8514851485148514]
[1531, 3.4615384615384617]
[1532, 4.095238095238095]
[1533, 3.84]
[1534, 3.619047619047619]
[1535, 3.896551724137931]
[1536, 4.222222222222222]
[1537, 3.763157894736842]
[1538, 3.989247311827957]
[1539, 4.37037037037037]
[1540, 3.805084745762712]
[1541, 4.423076923076923]
[1542, 3.6723549488054608]
[1543, 3.46242774566474]
[1544, 3.690909090909091]
[1545, 3.1013824884792625]
[1546, 3.754385964912281]
[1547, 3.9328358208955225]
[1548, 3.5833333333333335]
[1549, 3.619047619047619]
[1550, 3.9310344827586206]
[1551, 3.9397590361445785]
[1552, 3.6862745098039214]
[1553, 3.7209302325581395]
[1554, 3.806451612903226]
[1555, 4.3544303797468356]
[1556, 3.208695652173913]
[1557, 3.982456140350877]
[1558, 4.1

[1849, 3.7083333333333335]
[1850, 3.844155844155844]
[1851, 2.6984126984126986]
[1852, 3.5185185185185186]
[1853, 4.1210191082802545]
[1854, 2.817073170731707]
[1855, 3.144578313253012]
[1856, 4.6940298507462686]
[1857, 4.2682926829268295]
[1858, 3.9591836734693877]
[1859, 3.5652173913043477]
[1860, 3.310580204778157]
[1861, 3.3369565217391304]
[1862, 4.4]
[1863, 4.5]
[1864, 3.3043478260869565]
[1865, 3.5808383233532934]
[1866, 4.093525179856115]
[1867, 2.962962962962963]
[1868, 3.6296296296296298]
[1869, 3.9166666666666665]
[1870, 3.7974683544303796]
[1871, 3.7264957264957266]
[1872, 3.8181818181818183]
[1873, 3.48989898989899]
[1874, 3.59375]
[1875, 3.6153846153846154]
[1876, 3.4545454545454546]
[1877, 3.129251700680272]
[1878, 3.6506024096385543]
[1879, 3.931558935361217]
[1880, 3.344502617801047]
[1881, 4.333333333333333]
[1882, 3.780269058295964]
[1883, 3.331034482758621]
[1884, 3.867043847241867]
[1885, 4.157894736842105]
[1886, 3.923076923076923]
[1887, 3.384]
[1888, 3.617647058

[2258, 3.446927374301676]
[2259, 4.471615720524017]
[2260, 3.64]
[2261, 3.396694214876033]
[2262, 3.6842105263157894]
[2263, 3.707627118644068]
[2264, 3.63]
[2265, 3.6422413793103448]
[2266, 4.0495049504950495]
[2267, 3.547169811320755]
[2268, 4.260869565217392]
[2269, 3.36]
[2270, 3.4466019417475726]
[2271, 4.112462006079028]
[2272, 3.921259842519685]
[2273, 3.8450704225352115]
[2274, 3.775]
[2275, 3.864864864864865]
[2276, 4.324074074074074]
[2277, 3.392857142857143]
[2278, 3.417910447761194]
[2279, 3.638095238095238]
[2280, 4.105263157894737]
[2281, 4.0519480519480515]
[2282, 4.026595744680851]
[2283, 3.697674418604651]
[2284, 3.8846153846153846]
[2285, 3.6346153846153846]
[2286, 3.6]
[2287, 4.444444444444445]
[2288, 3.033644859813084]
[2289, 4.054054054054054]
[2290, 3.3393939393939394]
[2291, 4.0]
[2292, 3.1]
[2293, 4.321554770318021]
[2294, 4.112903225806452]
[2295, 4.409090909090909]
[2296, 3.3214285714285716]
[2297, 4.0476190476190474]
[2298, 3.325]
[2299, 2.92]
[2300, 3.884615

[2591, 3.8048780487804876]
[2592, 3.6334841628959276]
[2593, 4.536764705882353]
[2594, 3.106382978723404]
[2595, 3.352201257861635]
[2596, 3.7560975609756095]
[2597, 3.876923076923077]
[2598, 3.7037037037037037]
[2599, 3.6200873362445414]
[2600, 2.978021978021978]
[2601, 3.793103448275862]
[2602, 3.3448275862068964]
[2603, 3.883720930232558]
[2604, 3.8970588235294117]
[2605, 3.9361702127659575]
[2606, 4.22]
[2607, 4.17741935483871]
[2608, 4.008771929824562]
[2609, 4.306930693069307]
[2610, 3.108695652173913]
[2611, 3.347319347319347]
[2612, 3.0930232558139537]
[2613, 4.090909090909091]
[2614, 4.133333333333334]
[2615, 3.4918032786885247]
[2616, 3.58]
[2617, 3.5853658536585367]
[2618, 3.16]
[2619, 4.236559139784946]
[2620, 3.532051282051282]
[2621, 2.984126984126984]
[2622, 3.918918918918919]
[2623, 3.759259259259259]
[2624, 4.147058823529412]
[2625, 3.387323943661972]
[2626, 4.045454545454546]
[2627, 3.243298969072165]
[2628, 3.334975369458128]
[2629, 4.011029411764706]
[2630, 3.592592

[2998, 3.5]
[2999, 2.9407407407407407]
[3000, 3.2641509433962264]
[3001, 3.9935275080906147]
[3002, 4.217687074829932]
[3003, 3.9240506329113924]
[3004, 3.85]
[3005, 3.8018018018018016]
[3006, 4.153846153846154]
[3007, 2.8702928870292888]
[3008, 3.823529411764706]
[3009, 4.0]
[3010, 3.4380952380952383]
[3011, 4.315217391304348]
[3012, 2.5062111801242235]
[3013, 3.4539614561027836]
[3014, 3.570588235294118]
[3015, 3.4285714285714284]
[3016, 3.8292682926829267]
[3017, 3.2845303867403315]
[3018, 3.7]
[3019, 4.148148148148148]
[3020, 4.017647058823529]
[3021, 3.25]
[3022, 3.006666666666667]
[3023, 3.5161290322580645]
[3024, 3.63302752293578]
[3025, 4.108108108108108]
[3026, 2.761904761904762]
[3027, 4.217391304347826]
[3028, 3.743362831858407]
[3029, 3.914586070959264]
[3030, 3.769230769230769]
[3031, 3.904]
[3032, 4.278704612365064]
[3033, 3.601503759398496]
[3034, 3.9285714285714284]
[3035, 3.8125]
[3036, 4.525862068965517]
[3037, 4.21875]
[3038, 4.0423728813559325]
[3039, 4.409836065573

[3415, 4.0120481927710845]
[3416, 3.578723404255319]
[3417, 3.869565217391304]
[3418, 3.7914691943127963]
[3419, 4.033333333333333]
[3420, 4.3545454545454545]
[3421, 4.333333333333333]
[3422, 2.657963446475196]
[3423, 3.943217665615142]
[3424, 4.197183098591549]
[3425, 3.5386178861788617]
[3426, 3.975]
[3427, 3.763157894736842]
[3428, 4.0]
[3429, 3.6]
[3430, 3.41871921182266]
[3431, 3.806451612903226]
[3432, 3.2758620689655173]
[3433, 3.022727272727273]
[3434, 3.6264367816091956]
[3435, 3.8253968253968256]
[3436, 3.799019607843137]
[3437, 4.5]
[3438, 3.55]
[3439, 4.101123595505618]
[3440, 4.2592592592592595]
[3441, 2.90625]
[3442, 3.435483870967742]
[3443, 3.92]
[3444, 3.1]
[3445, 3.8819444444444446]
[3446, 4.472222222222222]
[3447, 3.8588235294117648]
[3448, 3.6153846153846154]
[3449, 4.171875]
[3450, 3.6031746031746033]
[3451, 3.870967741935484]
[3452, 4.458823529411765]
[3453, 3.37123745819398]
[3454, 3.5027624309392267]
[3455, 4.043478260869565]
[3456, 4.418181818181818]
[3457, 3.5

[3822, 3.4239130434782608]
[3823, 3.9510268562401265]
[3824, 3.004911591355599]
[3825, 2.9674134419551934]
[3826, 3.857142857142857]
[3827, 3.747311827956989]
[3828, 3.9285714285714284]
[3829, 3.008515815085158]
[3830, 4.051470588235294]
[3831, 3.401639344262295]
[3832, 4.111111111111111]
[3833, 3.6698717948717947]
[3834, 4.254448398576512]
[3835, 4.472527472527473]
[3836, 3.388235294117647]
[3837, 3.770408163265306]
[3838, 3.25]
[3839, 3.340909090909091]
[3840, 4.088235294117647]
[3841, 3.3445723684210527]
[3842, 3.687593423019432]
[3843, 2.6666666666666665]
[3844, 4.082089552238806]
[3845, 4.121621621621622]
[3846, 3.9571428571428573]
[3847, 2.727272727272727]
[3848, 4.153846153846154]
[3849, 3.1492537313432836]
[3850, 3.8671875]
[3851, 3.116279069767442]
[3852, 4.43859649122807]
[3853, 4.248407643312102]
[3854, 4.048780487804878]
[3855, 3.712871287128713]
[3856, 3.9361702127659575]
[3857, 3.925925925925926]
[3858, 4.277777777777778]
[3859, 3.414239482200647]
[3860, 3.649122807017543

[4238, 3.4249084249084247]
[4239, 4.117647058823529]
[4240, 3.9393939393939394]
[4241, 4.051020408163265]
[4242, 3.8244274809160306]
[4243, 4.056338028169014]
[4244, 3.55]
[4245, 3.630434782608696]
[4246, 3.7777777777777777]
[4247, 3.1315789473684212]
[4248, 3.764705882352941]
[4249, 3.233009708737864]
[4250, 3.923547400611621]
[4251, 3.5670103092783507]
[4252, 3.257142857142857]
[4253, 3.4171597633136095]
[4254, 4.416666666666667]
[4255, 4.121951219512195]
[4256, 3.8518518518518516]
[4257, 3.2805755395683454]
[4258, 3.715]
[4259, 3.6666666666666665]
[4260, 3.1450617283950617]
[4261, 3.187725631768953]
[4262, 3.6578947368421053]
[4263, 3.6578947368421053]
[4264, 4.238095238095238]
[4265, 3.8564593301435406]
[4266, 3.246376811594203]
[4267, 3.3783783783783785]
[4268, 3.264516129032258]
[4269, 3.7709251101321586]
[4270, 3.4583333333333335]
[4271, 2.994296577946768]
[4272, 3.4601769911504423]
[4273, 4.666666666666667]
[4274, 2.8823529411764706]
[4275, 3.806451612903226]
[4276, 3.780487804

[4639, 4.288461538461538]
[4640, 2.6578947368421053]
[4641, 4.025]
[4642, 3.696969696969697]
[4643, 3.0398009950248754]
[4644, 3.4335664335664338]
[4645, 4.174603174603175]
[4646, 3.128205128205128]
[4647, 3.4871220604703246]
[4648, 3.7837837837837838]
[4649, 4.818181818181818]
[4650, 2.9791666666666665]
[4651, 3.5476190476190474]
[4652, 4.26]
[4653, 3.396039603960396]
[4654, 4.0625]
[4655, 3.675438596491228]
[4656, 3.8858447488584473]
[4657, 4.0]
[4658, 2.3758992805755397]
[4659, 4.107843137254902]
[4660, 4.0]
[4661, 4.019607843137255]
[4662, 2.857142857142857]
[4663, 3.2977099236641223]
[4664, 4.157894736842105]
[4665, 4.090909090909091]
[4666, 3.4548022598870056]
[4667, 4.378378378378378]
[4668, 4.28125]
[4669, 3.688888888888889]
[4670, 3.378640776699029]
[4671, 3.8802395209580838]
[4672, 3.5652173913043477]
[4673, 3.8181818181818183]
[4674, 4.094736842105263]
[4675, 3.795795795795796]
[4676, 3.606060606060606]
[4677, 4.2272727272727275]
[4678, 3.616279069767442]
[4679, 3.3064516129

[5041, 4.2105263157894735]
[5042, 3.472826086956522]
[5043, 4.2]
[5044, 4.087591240875913]
[5045, 3.176470588235294]
[5046, 3.6497695852534564]
[5047, 3.523510971786834]
[5048, 4.382022471910112]
[5049, 4.046875]
[5050, 3.988235294117647]
[5051, 3.7333333333333334]
[5052, 4.190476190476191]
[5053, 3.8225108225108224]
[5054, 3.3384615384615386]
[5055, 3.6904761904761907]
[5056, 4.479381443298969]
[5057, 3.554054054054054]
[5058, 4.340425531914893]
[5059, 3.5588235294117645]
[5060, 4.0]
[5061, 3.6492890995260665]
[5062, 4.208333333333333]
[5063, 3.849557522123894]
[5064, 4.070707070707071]
[5065, 3.6830188679245284]
[5066, 4.121212121212121]
[5067, 4.142857142857143]
[5068, 4.054545454545455]
[5069, 4.76]
[5070, 3.5471311475409837]
[5071, 4.1234567901234565]
[5072, 4.271186440677966]
[5073, 4.52]
[5074, 3.433639947437582]
[5075, 4.258620689655173]
[5076, 3.4403669724770642]
[5077, 3.5919811320754715]
[5078, 3.966666666666667]
[5079, 3.4285714285714284]
[5080, 4.0]
[5081, 3.80198019801980

[5453, 3.639676113360324]
[5454, 4.15625]
[5455, 3.5555555555555554]
[5456, 3.619047619047619]
[5457, 3.578034682080925]
[5458, 3.686224489795918]
[5459, 3.966292134831461]
[5460, 4.364705882352941]
[5461, 4.083333333333333]
[5462, 3.9166666666666665]
[5463, 3.85]
[5464, 4.230088495575221]
[5465, 3.272727272727273]
[5466, 4.0964912280701755]
[5467, 3.6296296296296298]
[5468, 3.6233766233766236]
[5469, 4.156521739130435]
[5470, 3.951923076923077]
[5471, 3.76]
[5472, 2.8990536277602525]
[5473, 3.95]
[5474, 3.595744680851064]
[5475, 4.045092838196286]
[5476, 4.176470588235294]
[5477, 3.6]
[5478, 3.676470588235294]
[5479, 3.638095238095238]
[5480, 3.3866666666666667]
[5481, 3.425925925925926]
[5482, 3.928]
[5483, 3.8823529411764706]
[5484, 4.430379746835443]
[5485, 3.763157894736842]
[5486, 4.116279069767442]
[5487, 4.297872340425532]
[5488, 3.4150197628458496]
[5489, 4.128571428571429]
[5490, 3.2903225806451615]
[5491, 3.696078431372549]
[5492, 2.9526315789473685]
[5493, 3.340314136125654

[5862, 4.6]
[5863, 3.9047619047619047]
[5864, 4.205128205128205]
[5865, 3.3300970873786406]
[5866, 3.875]
[5867, 3.6875]
[5868, 4.134328358208955]
[5869, 3.5789473684210527]
[5870, 3.9743589743589745]
[5871, 4.17]
[5872, 3.3688212927756656]
[5873, 4.242424242424242]
[5874, 3.5451505016722407]
[5875, 3.8333333333333335]
[5876, 3.8260869565217392]
[5877, 3.6818181818181817]
[5878, 3.632279534109817]
[5879, 3.7818181818181817]
[5880, 3.2085561497326203]
[5881, 3.567857142857143]
[5882, 3.7]
[5883, 3.3461538461538463]
[5884, 3.8846153846153846]
[5885, 4.082644628099174]
[5886, 3.2708757637474544]
[5887, 3.6463414634146343]
[5888, 3.1831442463533226]
[5889, 3.9076923076923076]
[5890, 3.911854103343465]
[5891, 3.6666666666666665]
[5892, 4.087719298245614]
[5893, 3.168918918918919]
[5894, 3.8956521739130436]
[5895, 3.5]
[5896, 2.5528846153846154]
[5897, 3.8867924528301887]
[5898, 3.7586206896551726]
[5899, 3.380952380952381]
[5900, 3.296]
[5901, 3.2]
[5902, 3.632183908045977]
[5903, 3.7662337

In [51]:
list2 = []
for i in user_id:
    a= np.mean(data[data[:,0]==i,2])
    list1 = [i,a]
    print(list1,end="\n")
    np.array(list1) 

[6040, 3.5777126099706744]

In [50]:
list1

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.4479166666666665],
 [41, 

In [39]:
np.array(list2)

array([[1.00000000e+00, 4.18867925e+00],
       [2.00000000e+00, 3.71317829e+00],
       [3.00000000e+00, 3.90196078e+00],
       ...,
       [6.03800000e+03, 3.80000000e+00],
       [6.03900000e+03, 3.87804878e+00],
       [6.04000000e+03, 3.57771261e+00]])

In [46]:

#1번 사용자의 평점 평균
data[data[:,0]==1][:,2].mean()

4.188679245283019

In [48]:
list1=[]
for user in user_id:
    user_mean=data[data[:,0]==user][:,2].mean()
    #1~6040번의 평균
    list1.append([user,user_mean])
    

In [49]:
list1

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.4479166666666665],
 [41, 

# Pandas 라이브러리