In [5]:
import module_test

In [7]:
module_test.add(2,4)

6

#### from module_test import add 로 가져올수도 있는데 add만 사용가능함

NumPy - 고성능 과학계산을 위한 데이터 분석 라이브러리

Pandas - 행과 열로 구성된 표 형식의 데이터를 지원하는 라이브러리

Matplotlib - 2D 그래프로 시각화가 가능한 라이브러리

In [8]:
import numpy as np

In [9]:
list1 = [1, 2, 3, 4, 5]

In [10]:
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [11]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr.shape

(5,)

In [13]:
arr2.shape

(2, 3)

In [14]:
print(arr)
print(arr.size)

[1 2 3 4 5]
5


In [15]:
print(arr2)
print(arr2.size)

[[1 2 3]
 [4 5 6]]
6


In [16]:
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [17]:
print(arr2)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
int32


In [18]:
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [19]:
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [22]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("배열의 크기 : ",arr3.shape)
print("배열의 차원 : ",arr3.ndim)
print("배열의 개수 : ",arr3.size)

배열의 크기 :  (2, 2, 2)
배열의 차원 :  3
배열의 개수 :  8


In [23]:
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
arr_zeros = np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
arr_ones = np.ones((3,3,4))
arr_ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [35]:
arr_full = np.full((3,3,2),7)
arr_full

array([[[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]]])

In [36]:
list = []
for i in range(1,51):
    list.append(i)
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [38]:
arr = np.array(list)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [39]:
arr = np.arange(1,51)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [41]:
arr = np.arange(1,51,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [51]:
arr_type = np.array([1.2,2.3,3.4], dtype=np.int64)
arr_type

array([1, 2, 3], dtype=int64)

In [45]:
2**32

4294967296

In [46]:
2**64

18446744073709551616

In [52]:
arr_type = arr_type.astype("float64")
print(arr_type)
print(arr_type.dtype)

[1. 2. 3.]
float64


In [64]:
arr = np.random.rand(2,3)
arr

array([[0.61980619, 0.57143985, 0.23256822],
       [0.52671704, 0.15202166, 0.42822438]])

In [115]:
arr = np.random.randint(2,10)
arr

4

In [117]:
arr = np.random.randint(2,10, size=(2,3))
arr

array([[7, 5, 7],
       [9, 3, 7]])

In [118]:
data = np.loadtxt("height_weight.txt", delimiter=",")
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [133]:
data[1]/((data[0]/100)*(data[0]/100))

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [144]:
arr2 = np.arange(50).reshape(5,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [145]:
arr2[2,1]

21

In [146]:
arr = np.random.randint(1,10,size=(2,5))
arr

array([[1, 4, 4, 8, 4],
       [7, 5, 5, 9, 7]])

In [147]:
print(arr.sum())
print(np.sum(arr))

54
54


In [148]:
#가로끼리의 연산
arr.sum(axis=1)

array([21, 33])

In [149]:
#세로끼리의 연산
sum(arr)

array([ 8,  9,  9, 17, 11])

# boolean 색인

In [ ]:
name